openapi: 3.0.3
info:
  title: Spardha Microservices API
  description: >-
    [Base Url: https://microservice-fmi4.onrender.com/api/v1]
    
  version: 1.0.11
servers:
  - url: https://microservice-fmi4.onrender.com/api/v1
tags:
  - name: Games
    description: To add, get, edit, delete Games
paths:
  /games/:
    post:
      tags:
        - Games
      summary: Add a new Game Fixture
      description: Add a new Game Fixture
      operationId: addGame
      requestBody:
        description: Add a new Game Fixture
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/GameModelWithoutId'
                - type: object
                  required:
                    - game_name
                    - game_start
                    - game_venue
                    - team1
                    - team2

      responses:
        '200':
          description: Addition of Game successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddGame'
        '400':
          description: Invalid Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'
    get:
      tags:
        - Games
      summary: Getting all games
      description: Get all games
      operationId: getAllGames
      responses:
        '200':
          description: Fetched All Games successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetGames"
        '400':
          description: Invalid Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'
  /games/{game_id}:
    patch:
      tags:
        - Games
      summary: Updates a game
      description: Edit a Game
      operationId: updateGame
      parameters:
        - name: game_id
          in: path
          description: 'Id of the game to be edited'
          required: true
          schema:
            type: string
      requestBody:
        description: You can send one or more than one fields in the request body to update
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameModelWithoutId"
      responses:
        '200':
          description: Game edited successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditGame'
        '400':
          description: Invalid Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: Game Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Game not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'
    delete:
      tags:
        - Games
      summary: Deletes a game
      description:  Deletes a game with the given id
      operationId: deleteGame
      parameters:
        - name: game_id
          in: path
          description: 'Id of the game to be deleted'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Game deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteGame"
          
        '400':
          description: Invalid Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: Game Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Game not found: No deletion occured"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'
            
components:
  schemas:
    GameModelWithoutId:
      type: object
      properties:
        game_name:
          type: string
          example: Cricket
        game_start:
          type: string
          format: date-time
        game_venue:
          type: string
          example: Rajputana Grounds
        team1:
          type: string
          example: College 1
        team2:
          type: string
          example: College 2
        is_completed:
          type: boolean
          example: false
    
    GameModel:
      allOf:
        - type: object
          properties:
            _id:
              type: string
              example: 64f1f42a4d4a7b6444b20cdb
        - $ref: '#/components/schemas/GameModelWithoutId'
          
    GameArray:
      type: array
      items:
        $ref: '#/components/schemas/GameModel'
      example: 
          - _id: 64f1f42a4d4a7b6444b20cdb
            game_name: Cricket
            game_start: 2023-09-01T18:09:58.462Z
            game_venue: Rajputana grounds
            team1: College 1
            team2: College 2
    GetGames:
      properties:
        success:
          type: boolean
          example: true
        length:
          type: number
          example: 1
        data: 
          $ref: "#/components/schemas/GameArray"
    AddGame:
      properties:
        success:
          type: boolean
          example: true
        message: 
          type: string
          example: Game Added successfully
        game_id:
          type: string
          example: 64f1f42a4d4a7b6444b20cdb
      
    EditGame:
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Game edited successfully
        editedGame: 
          $ref: "#/components/schemas/GameModel"
          
    DeleteGame:
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Game deleted successfully
        deletedGame: 
          $ref: "#/components/schemas/GameModel"
    ValidationError:
      properties:
        success: 
          type: boolean
          example: false
        message:
          type: string
          example: Invalid Input
        errors:
          type: array
          example:
            - type: field
              value: ''
              msg: Game name cannot be empty
              path: game_name
              location: body
            - type: field
              value: 'Saturday 9am'
              msg: Invalid date format. Use ISO8601 format for game start date
              path: game_name
              location: body
    GeneralError:
      properties:
        success: 
          type: boolean
          example: false
        message:
          type: string
          example: Internal Server Error
